### ISSUE TITLE
RedirectResponse

### ISSUE THREAD

**Issue by remdan** [saxulum/saxulum-crud#1]
I need to return different RedirectResponses after form validate.
Example: dependent on the submitted button... 
```php
if ('POST' === $request->getMethod()) {
            $form->handleRequest($request);
            if ($form->isValid()) {

                $this->crudCreatePrePersist($object);

                $em = $this->crudManagerForClass($this->crudObjectClass());
                $em->persist($object);
                $em->flush();

                $this->crudCreatePostFlush($object);

                $this->crudFlashMessage($request, 'success', sprintf('%s.create.flash.success', $this->crudName()));

                if ($form->get('submitadd')->isClicked()) {
                    return new RedirectResponse($this->generateUrl('instructor_create'));
                }

                return new RedirectResponse($this->crudCreateRedirectUrl($object), 302);
            } else {
                $this->crudFlashMessage($request, 'error', sprintf('%s.create.flash.error', $this->crudName()));
            }
        }
```

**Comment by dominikzogg** [comment]
@Gladhon what would you do to solve this issue?

Inject the form within each method, that its possible could be a solution

**Comment by Gladhon** [comment]
We are in the context of a CRUD-Controller, so we obviously have  only one form. Why not add and crudGetForm method, wich get back the current form.

**Comment by dominikzogg** [comment]
Its probably a good idea to solve it with a single object as parameter as for example events does. $parameter->getObject(), $parameter->getForm(), $parameter->getRequest() on each method (override, or hook)

**Comment by dominikzogg** [comment]
this is a to big change for a rc, which means this feature will be in v2

**Comment by dominikzogg** [comment]
This should solve the problem: https://github.com/saxulum/saxulum-crud/blob/master/src/Controller/CrudTrait.php#L105
